In [1]:
# Pandas library import kar rahe hain data handle karne ke liye
import pandas as pd

In [2]:
# CSV file ko read karke dataframe me store kar rahe hain
dh = pd.read_csv("house.csv")

In [3]:
dh

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1
...,...,...,...,...,...,...,...,...
409,410,2013.000,13.7,4082.01500,0,24.94155,121.50381,15.4
410,411,2012.667,5.6,90.45606,9,24.97433,121.54310,50.0
411,412,2013.250,18.8,390.96960,7,24.97923,121.53986,40.6
412,413,2013.000,8.1,104.81010,5,24.96674,121.54067,52.5
413,414,2013.500,6.5,90.45606,9,24.97433,121.54310,63.9

In [4]:
# Dataset ki basic information dekhne ke liye (columns, data types, null values)
dh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   No                                      414 non-null    int64
 1   X1 transaction date                     414 non-null    float64
 2   X2 house age                            414 non-null    float64
 3   X3 distance to the nearest MRT station  414 non-null    float64
 4   X4 number of convenience stores         414 non-null    int64
 5   X5 latitude                             414 non-null    float64
 6   X6 longitude                            414 non-null    float64
 7   Y house price of unit area              414 non-null    float64
dtypes: float64(6), int64(2)
memory usage: 26.0 KB

In [5]:
# Duplicate rows check karne ke liye
dh.duplicated().sum()

np.int64(0)

In [6]:
# columns ka name change kar rahy hain apni asani ke liye
dh = dh.rename(columns={
    "X1 transaction date": "transaction_date",
    "X2 house age": "house_age",
    "X3 distance to the nearest MRT station": "mrt_distance",
    "X4 number of convenience stores": "convenience_stores",
    "X5 latitude": "latitude",
    "X6 longitude": "longitude",
    "Y house price of unit area": "price"
})

In [7]:
dh

,No,transaction_date,house_age,mrt_distance,convenience_stores,latitude,longitude,price
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1
...,...,...,...,...,...,...,...,...
409,410,2013.000,13.7,4082.01500,0,24.94155,121.50381,15.4
410,411,2012.667,5.6,90.45606,9,24.97433,121.54310,50.0
411,412,2013.250,18.8,390.96960,7,24.97923,121.53986,40.6
412,413,2013.000,8.1,104.81010,5,24.96674,121.54067,52.5
413,414,2013.500,6.5,90.45606,9,24.97433,121.54310,63.9

In [8]:
# No ko drop kar rahy hein q k iski zaroorat nahi
dh = dh.drop("No" ,axis = 1)

In [9]:
dh

,transaction_date,house_age,mrt_distance,convenience_stores,latitude,longitude,price
0,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1
...,...,...,...,...,...,...,...
409,2013.000,13.7,4082.01500,0,24.94155,121.50381,15.4
410,2012.667,5.6,90.45606,9,24.97433,121.54310,50.0
411,2013.250,18.8,390.96960,7,24.97923,121.53986,40.6
412,2013.000,8.1,104.81010,5,24.96674,121.54067,52.5
413,2013.500,6.5,90.45606,9,24.97433,121.54310,63.9

In [10]:
# Independent variables (features) select kar rahe hain (price ke ilawa sab)
x = dh.drop("price" , axis = 1)

# Dependent variables (Target) select kar rahe hain (Only price)
y = dh["price"]

In [11]:
# Dataset ko training aur testing me split karne ke liye function import kar rahe hain
from sklearn.model_selection import train_test_split

# 70% Training aur 30% Testing data bana rahe hain
X_train , X_test , y_train , y_test = train_test_split (x , y , test_size = 0.3 , random_state = 42)

In [12]:
# Linear Regression model import kar rahe hain
from sklearn.linear_model import LinearRegression

In [13]:
# Model create kar rahe hain
model = LinearRegression()

# Training data par model train (fit) kar rahe hain
model.fit(X_train , y_train)

LinearRegression()

In [14]:
# Model ka Coefficient dekhne ke liye
model.coef_

array([ 5.84779706e+00, -2.42545813e-01, -5.13873381e-03,  1.07449530e+00,
        2.39096949e+02, -5.22351591e+01])

In [15]:
# Model ka Interceopt dekhny ke liye
model.intercept_

np.float64(-11350.740518771496)

In [16]:
# Training data par predictions nikal rahe hain
y_pred_train = model.predict(X_train)

In [17]:
from sklearn.metrics import mean_squared_error , r2_score
from math import sqrt

In [18]:
# Training data ka Mean Squared Error calculate kar rahe hain
mean_squared_error(y_train , y_pred_train)

79.25684509898059

In [19]:
# Training data ka Root Mean Squared Error calculate kar rahe hain
sqrt(mean_squared_error(y_train , y_pred_train))

8.902631358142411

In [20]:
# Training data ka R2_Score calculate kar rahe hain
r2_score(y_train , y_pred_train)

0.5862063121758456

In [21]:
# Testing data par predictions nikal rahe hain
y_pred_test = model.predict(X_test)

In [22]:
# Testing data ka Mean Squared Error calculate kar rahe hain
mean_squared_error(y_test , y_pred_test)

73.56837932850077

In [23]:
# Testing data ka root Mean Squared Error calculate kar rahe hain
sqrt(mean_squared_error(y_test , y_pred_test))

8.577201136064186

In [24]:
# Testing data ka R2_Score calculate kar rahe hain
r2_score(y_test , y_pred_test)

0.5600638168604352

In [26]:
# Function bana rahy hein Charges Pridect karne ke liye
def House_Price_Predictor(transaction_date , house_age , mrt_distance , convenience_stores , latitude , longitude):
    price = model.predict([[transaction_date , house_age , mrt_distance , convenience_stores , latitude , longitude]])
    return (price)

# User se Input le rahy hein
Transaction_Date   = float(input("Enter Transaction Date : "))
House_Age          = float(input("Enter House Age : "))
MRT_Distance       = float(input("Enter MRT Distance : "))
Convenience_Stores = float(input("Enter Convenience Stores : "))
Latitude           = float(input("Enter Latitude : "))
Longitude          = float(input("Enter Longitude : "))

result = House_Price_Predictor(Transaction_Date , House_Age , MRT_Distance , Convenience_Stores , Latitude , Longitude)
print(result)

Enter Transaction Date :  2013.13
Enter House Age :  8.5
Enter MRT Distance :  600
Enter Convenience Stores :  12
Enter Latitude :  29
Enter Longitude :  130

[572.6250798]

C:\Users\Lenovo\anaconda2\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [ ]:
dh

##